name: mangueapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # bloc related
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

  #database
  sqflite: ^2.0.3+1

  #bluetooth
  flutter_blue: ^0.8.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  #assets:
